# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(f'Version: {np.__version__}')
np.show_config()

Version: 1.25.2
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/max1m/miniconda3/envs/LabWork1\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/max1m/miniconda3/envs/LabWork1\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/max1m/miniconda3/envs/LabWork1\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/max1m/miniconda3/envs/LabWork1\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/max1m/miniconda3/envs/LabWork1\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/max1m/miniconda3/envs/LabWork1\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/max1m/miniconda3/envs/LabWork1\\Library\\l

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
temp = np.zeros(10)
print(temp)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
temp = np.zeros(10)
print(f'{(temp.size * temp.itemsize)} bytes')

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
# python -c "import numpy; numpy.info(numpy.zeros)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
temp = np.zeros(10)
temp[4] = 1
print(temp)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
temp = np.arange(10, 50)
print(temp)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
temp = np.arange(10)
print(temp)
temp = temp[::-1]
print(temp)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
temp = np.arange(9).reshape(3, 3)
print(temp)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
temp = np.nonzero([1,2,0,0,4,0])
print(temp)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
temp = np.eye(3)
print(temp)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
temp = np.random.random((3, 3, 3))
print(temp)

[[[0.63316264 0.83554898 0.00800816]
  [0.3671967  0.64329299 0.52473572]
  [0.98473826 0.50896952 0.38633371]]

 [[0.76069682 0.48570713 0.05152142]
  [0.10355824 0.02953865 0.04020979]
  [0.38162303 0.41644357 0.96628685]]

 [[0.96039787 0.66981094 0.79427864]
  [0.83730016 0.54380097 0.36786801]
  [0.17295133 0.67880423 0.6505794 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
temp = np.random.random((10, 10))
temp_min,temp_max = temp.min(), temp.max()
print(temp_min, temp_max)

0.0024953002889069875 0.9980405483403075


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
temp = np.random.random(30)
m = temp.mean()
print(m)

0.5449802845079194


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
temp = np.ones((10, 10))
temp[1:-1, 1:-1] = 0
print(temp)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
temp = np.ones((10, 10))
temp = np.pad(temp, pad_width=1, mode='constant', constant_values=0)
print(temp)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(np.nan)
print(False)
print(False)
print(np.nan)
print(True)
print(False)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
temp = np.diag(1 + np.arange(4), k=-1)
print(temp)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
temp = np.zeros((8, 8), dtype=int)
temp[1::2, ::2] = 1
temp[::2, 1::2] = 1
print(temp)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
temp = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(temp)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
temp = np.random.random((5, 5))
temp = (temp - np.mean (temp)) / (np.std (temp))
print(temp)

[[-0.50607354  0.16203332 -1.5323713  -0.95108791  0.26547825]
 [ 1.18175859  1.37892038 -0.55144159  1.45508137 -0.31773697]
 [-1.28160861 -0.64016633  1.42930549 -1.35824313  1.0028868 ]
 [-0.26186498 -0.05223152 -0.62771278  1.3317368  -1.08627607]
 [-0.82445457 -0.57869662 -0.45406375  1.30498196  1.51184672]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
temp = np.dot(np.random.random((5, 3)), np.random.random((3, 2)))
print(temp)

[[0.59921556 0.84075286]
 [0.54463277 0.82710413]
 [0.52326062 0.80840957]
 [0.44285528 0.7269654 ]
 [0.51147011 0.84944433]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
temp = np.arange(11)
temp[(3 < temp) & (temp < 8)] *= -1
print(temp)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
temp = np.ones(5)
temp ** temp
## 2 << temp >> 2 is illegal
temp < - temp
1j * temp
temp / 1 / 1
## temp<temp>temp is illegal

array([1., 1., 1., 1., 1.])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\max1m\AppData\Local\Temp\ipykernel_15924\1422587819.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\max1m\AppData\Local\Temp\ipykernel_15924\1422587819.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\max1m\AppData\Local\Temp\ipykernel_15924\1422587819.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
temp = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(temp)), temp))

# More readable but less efficient
print(np.where(temp > 0, np.ceil(temp), np.floor(temp)))

[ 2. -4. -1.  6. -6. -7. -7. -6. -4. 10.]
[ 2. -4. -1.  6. -6. -7. -7. -6. -4. 10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
temp1 = np.random.randint(0,10,10)
temp2 = np.random.randint(0,10,10)
print(np.intersect1d(temp1,temp2))

[1 2 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
# defaults = np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
print(False)

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
print(np.datetime64('today') - np.timedelta64(1))
print(np.datetime64('today'))
print(np.datetime64('today') + np.timedelta64(1))

2023-10-24
2023-10-25
2023-10-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
temp = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(temp)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A = np.arange(4.0,8.0)
B = np.arange(1.0,5.0)
print(A)
print(B)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)
print(B)

[4. 5. 6. 7.]
[1. 2. 3. 4.]
[-10.  -17.5 -27.  -38.5]
[ 5.  7.  9. 11.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [36]:
temp = np.random.uniform(0, 10, 10)
print(temp - temp % 1)
print(temp // 1)
print(np.floor(temp))
print(np.trunc(temp))

[2. 9. 4. 6. 4. 8. 9. 4. 3. 3.]
[2. 9. 4. 6. 4. 8. 9. 4. 3. 3.]
[2. 9. 4. 6. 4. 8. 9. 4. 3. 3.]
[2. 9. 4. 6. 4. 8. 9. 4. 3. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
temp = np.tile(np.arange(0, 5), (5, 1))
print(temp)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [38]:
def generate():
    for i in range(10):
        yield i
temp = np.fromiter(generate(), dtype=float, count=-1)
print(temp)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
temp = np.linspace(0, 1, 11, endpoint=False)[1:]
print(temp)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [40]:
temp = np.random.random(10)
temp.sort()
print(temp)

[0.03693444 0.22585147 0.23698345 0.47534344 0.62977718 0.72544001
 0.79611079 0.83832855 0.88793937 0.94905914]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [41]:
temp = np.arange(10)
np.add.reduce(temp)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [42]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [43]:
temp = np.zeros(10)
temp.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [44]:
temp = np.random.random((10, 2))
X,Y = temp[:, 0], temp[:, 1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.85420108 1.01102663 1.10513275 0.66240638 0.88719781 1.23929298
 0.62562075 0.90928526 0.94374421 0.78594941]
[0.05297157 1.34127822 0.92641652 0.60483763 0.31579364 0.68858957
 0.3715515  0.6555163  0.79538016 0.99713892]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [45]:
temp = np.random.random(10)
temp[temp.argmax()] = 0
print(temp)

[0.03292233 0.54315988 0.02786638 0.02650919 0.28561078 0.18649244
 0.63475933 0.27137557 0.8515413  0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [46]:
temp = np.zeros((5, 5), [('x', float), ('y', float)])
temp['x'], temp['y'] = np.meshgrid(np.linspace(0, 1, 5),
                                   np.linspace(0,1,5))
print(temp)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [47]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [48]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [49]:
np.set_printoptions(threshold=float("inf"))
temp = np.zeros((30, 30))
print(temp)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
temp = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(temp - v)).argmin()
print(temp[index])

50


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [51]:
temp = np.zeros(10, [('position', [('x', float, 1),
                                   ('y', float, 1)]),
                     ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(temp)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\max1m\AppData\Local\Temp\ipykernel_15924\498994993.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  temp = np.zeros(10, [('position', [('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [52]:
temp = np.random.random((100, 2))
X,Y = np.atleast_2d(temp[:, 0], temp[:, 1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.27791406 0.22884306 0.30009422 0.18546771 0.69057303
  0.25965354 0.57716829 0.6542546  0.32923707 0.1215078  0.59364273
  0.74587794 0.80706495 0.29354654 0.27165344 0.34032124 0.21630626
  0.68599714 0.32657952 0.16824281 0.45215641 0.24299856 0.57721126
  0.55551466 0.53901429 0.86176304 0.24134023 0.17180098 0.12411789
  0.58837971 0.38674337 0.15661235 0.53185056 0.12822053 0.4900985
  0.21936414 0.59639285 0.28235814 0.17994891 0.22625296 0.30116269
  0.66074166 0.64407879 0.17569337 0.69892512 0.385374   0.15494888
  0.35343404 0.63170687 0.81020685 0.08413885 0.23598385 0.35592642
  0.59439336 0.65085007 0.40473109 0.30190148 0.30953469 0.58645628
  0.36167586 0.43648165 0.43451086 0.67901534 0.24831469 0.84012121
  0.89237698 0.54077782 0.37877757 0.68920617 0.3811564  0.13580585
  0.70657492 0.25510669 0.44978835 0.36308841 0.73579456 0.59021817
  0.34734255 0.36415212 0.25956269 0.23207298 0.81566317 0.2530153
  0.8529877  0.48160502 0.28730517 0.48773781 0.31

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [53]:
temp = (np.random.rand(10) * 100).astype(np.float32)
Y = temp.view(np.int32)
Y[:] = temp
print(Y)

[91 40 61 44 80 87 64 50 46 42]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [54]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
temp = np.genfromtxt(s, delimiter=",", dtype=np.int64)
print(temp)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [55]:
temp = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(temp):
    print(index, value)
for index in np.ndindex(temp.shape):
    print(index, temp[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [56]:
mean = [0, 0]  # Mean values for x and y
cov = [[1, 0], [0, 1]]  # Covariance matrix

# Generate a 2D Gaussian-like array
size = (100, 100)  # Size of the array (e.g., 100x100)
gaussian_array = np.random.multivariate_normal(mean, cov, size)
print(gaussian_array)

[[[-4.61958800e-01 -8.81025074e-01]
  [-6.79248694e-01  3.98001911e-01]
  [ 1.64631494e+00  1.43086034e+00]
  [ 9.67737362e-01 -5.21490737e-02]
  [ 2.96363869e-02  4.10120894e-02]
  [-1.83206309e-01  2.46790391e-01]
  [-5.68561182e-04 -8.44615355e-01]
  [-4.01637748e-01  4.10943314e-01]
  [ 9.34466486e-01 -1.26034875e+00]
  [ 2.73274155e+00 -7.10960487e-01]
  [ 1.11836269e+00  4.31868376e-01]
  [-1.06841531e+00  1.00327947e-01]
  [-4.21167496e-01 -1.99945588e-01]
  [ 1.87734515e-02 -1.13533686e+00]
  [-7.55535752e-01 -1.72477513e-01]
  [-1.92764700e+00  1.32369074e+00]
  [ 1.78614427e+00 -2.13924257e-01]
  [ 9.49208561e-01  9.99002520e-01]
  [-5.80024228e-01  3.94533663e-01]
  [-3.24289997e-01 -1.16338345e+00]
  [-2.13502810e+00  1.71633177e+00]
  [-1.97697338e-01 -2.93374698e-01]
  [-2.39178033e-01  6.98941664e-01]
  [ 2.63060261e-01 -7.48105576e-02]
  [-3.59126652e-01 -6.11256124e-01]
  [-3.91339071e-01 -5.95659679e-01]
  [-4.85535193e-01 -6.14570763e-01]
  [ 8.48585674e-01 -8.664590

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [57]:
n = 10
p = 5
temp = np.zeros((n,n))
np.put(temp, np.random.choice(range(n*n), p, replace=False),1)
print(temp)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [58]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[ 0.42941795  0.14623757  0.231894   -0.39069292 -0.32419316  0.36286407
  -0.16658143 -0.35990297 -0.39420888  0.46516578]
 [-0.07782553  0.30740422  0.27354707  0.32805981 -0.39540211  0.02489123
  -0.27606879  0.13990224 -0.19402926 -0.13047888]
 [ 0.09871336 -0.13317302 -0.18119522 -0.38129844  0.22777517  0.38454712
  -0.15350689  0.4182481  -0.2169659  -0.06314428]
 [ 0.2709758   0.0759631   0.09589491  0.13227477  0.10745706 -0.51344802
   0.20975387 -0.12054075  0.19719352 -0.45552426]
 [ 0.29569464 -0.38671675  0.23193862  0.39580745 -0.55087216 -0.40382093
   0.34052487  0.29849256 -0.50328275  0.28223446]]


#### 59. How to sort an array by the nth column? (★★☆)

In [59]:
temp = np.random.randint(0, 10, (3, 3))
print(temp)
print(temp[temp[:, 1].argsort()])

[[4 2 3]
 [9 5 5]
 [8 4 7]]
[[4 2 3]
 [8 4 7]
 [9 5 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [60]:
temp=np.array([
    [5,2,np.nan],
    [5,np.nan,np.nan],
    [1,2,np.nan]
])
print(np.isnan(temp).all(axis=0))

[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [61]:
temp = np.random.uniform(0, 1, 10)
print(temp)
temp1 = 0.2
m = temp.flat[np.abs(temp - temp1).argmin()]
print(m)

[0.2982216  0.7973136  0.01866173 0.70516411 0.76662334 0.2230036
 0.22633911 0.51057709 0.24373372 0.60150447]
0.22300360164747135


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [62]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [63]:
class Array(np.ndarray):
    def __new__(cls, array, name):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

temp = Array(np.arange(10), "Bob")
print (temp.name)

Bob


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [64]:
temp1 = np.ones(10)
temp2 = np.random.randint(0,len(temp1),15)
np.add.at(temp1, temp2, 1)
print(temp2)
print(temp1)

[2 1 8 7 4 3 1 8 7 1 5 0 3 8 6]
[2. 4. 2. 3. 2. 2. 2. 3. 4. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [65]:
X = [1,2,3,4,5,6]
I = [6,3,1,7,4,2]
F = np.bincount(I,X)
print(F)

[0. 3. 6. 2. 5. 0. 1. 4.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [66]:
w, h = 4, 4
I = np.random.randint(0, 4, (w, h, 3)).astype(np.ubyte)
unique = np.unique(I.reshape(-1, 3), axis=0)
n = len(unique)
print(n)

14


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [67]:
temp = np.random.randint(0,5,(3,4,3,4))
sum = temp.sum(axis=(-2,-1))
print(sum)

[[21 27 22 28]
 [23 34 21 27]
 [22 23 30 14]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [68]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.55392333 0.49537169 0.56124067 0.61435239 0.48424499 0.5209626
 0.64111484 0.3476394  0.5574053  0.48700727]


#### 69. How to get the diagonal of a dot product? (★★★)

In [69]:
temp1 = np.random.uniform(0,1,(5,5))
temp2 = np.random.uniform(0,1,(5,5))

np.diag(np.dot(temp1, temp2))

array([2.41194332, 0.94264548, 0.63365348, 1.020117  , 1.15889125])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [70]:
temp = np.array([1, 2, 3, 4, 5])
temp2 = np.zeros(len(temp) + (len(temp) - 1) * 3)
temp2[::4] = temp
print(temp2)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [71]:
temp1 = np.random.rand(5, 5, 3)
temp2 = np.random.rand(5, 5)
result = temp1 * temp2[:, :, np.newaxis]
print(result)

[[[5.29524093e-02 6.79435205e-02 2.47575859e-01]
  [4.47742507e-01 3.27227836e-01 4.91442514e-01]
  [4.94205206e-01 2.96933793e-01 4.65418999e-01]
  [3.54193054e-02 3.87405132e-01 5.49150594e-01]
  [3.86019171e-01 3.17155703e-01 2.08170540e-02]]

 [[1.43842704e-01 6.19274883e-02 2.74165120e-01]
  [2.31621914e-01 2.07905739e-01 1.46413895e-01]
  [1.09054127e-01 3.81990295e-01 1.16211441e-01]
  [6.17441522e-01 6.98819053e-01 5.20059775e-01]
  [1.60058417e-01 9.82654682e-02 1.99910569e-01]]

 [[2.52474589e-01 7.42639577e-02 7.33028840e-02]
  [1.24539387e-01 8.88797211e-02 1.35871073e-01]
  [8.15855572e-02 1.60223479e-01 4.01432481e-02]
  [1.84305641e-01 2.56114709e-01 3.67565184e-02]
  [4.99581166e-02 1.75691334e-02 5.60877644e-03]]

 [[1.77135613e-02 1.69213798e-02 2.65708996e-03]
  [1.65055748e-01 6.17931347e-01 4.19708068e-01]
  [5.94116602e-04 4.74106965e-04 2.75699869e-03]
  [3.39933045e-01 2.35855372e-01 1.77739657e-01]
  [1.80896125e-01 3.36426071e-01 3.55268087e-01]]

 [[3.7613458

#### 72. How to swap two rows of an array? (★★★)

In [72]:
temp = np.arange(25).reshape(5,5)
temp[[0,1]] = temp[[1,0]]
print(temp)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [99]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(faces)
print(G)

[[55  0 42]
 [60 64 60]
 [53 31 97]
 [16 10 37]
 [24 14 47]
 [13 97 48]
 [99 90 23]
 [33 50 10]
 [89 92 38]
 [41 48 55]]
[( 0, 42) ( 0, 55) (10, 16) (10, 33) (10, 37) (10, 50) (13, 48) (13, 97)
 (14, 24) (14, 47) (16, 37) (23, 90) (23, 99) (24, 47) (31, 53) (31, 97)
 (33, 50) (38, 89) (38, 92) (41, 48) (41, 55) (42, 55) (48, 55) (48, 97)
 (53, 97) (60, 60) (60, 64) (89, 92) (90, 99)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [74]:
C = np.bincount([1,3,4,6,6,8])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 3 4 6 6 8]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [75]:
from numpy.lib.stride_tricks import sliding_window_view

temp = np.random.rand(8)
print(temp)
print(sliding_window_view(temp, window_shape=3).mean(axis=-1))

[0.21016483 0.71558924 0.49634793 0.39593763 0.47957478 0.60002122
 0.22931821 0.576568  ]
[0.474034   0.53595827 0.45728678 0.49184454 0.43630474 0.46863581]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [76]:
Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [77]:
temp = np.random.randint(0,2,100)
np.logical_not(temp, out=temp)

temp = np.random.uniform(-1.0,1.0,100)
np.negative(temp, out=temp)

array([ 0.47080535,  0.16121808,  0.7267939 ,  0.51526124, -0.09334264,
        0.66728929, -0.54089897,  0.89924726,  0.90817908,  0.17646856,
       -0.57491276, -0.57963322, -0.48678491,  0.12600282,  0.37503329,
        0.2929553 ,  0.89684845, -0.62863458,  0.11805929,  0.68272925,
        0.57695669, -0.20790472,  0.15358504,  0.07587371, -0.34998297,
       -0.09552031, -0.68935862,  0.31413854,  0.85293529, -0.92519456,
       -0.08746502,  0.94515376,  0.26148113,  0.28743154, -0.90806115,
       -0.90623808,  0.66237902,  0.45679599,  0.88144499,  0.67428577,
        0.06962145,  0.21340377, -0.37701523,  0.43235172, -0.46649508,
        0.34292798, -0.22582211,  0.38004097, -0.17451415, -0.23488556,
        0.3528543 ,  0.90501605,  0.48544983, -0.59733704, -0.08569443,
       -0.459079  ,  0.66753277,  0.72984925,  0.73847149, -0.62654225,
       -0.39519844, -0.9242166 , -0.09875993, -0.42572593, -0.07217104,
       -0.6571521 , -0.73827147, -0.12424407,  0.4848493 , -0.98

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [78]:
def point_to_line_distances(p, P0, P1):
    p = np.array(p)
    P0 = np.array(P0)
    P1 = np.array(P1)

    v = P1 - P0
    w = p - P0

    t = np.sum(w * v, axis=1) / np.sum(v * v, axis=1)

    closest_points = P0 + t[:, np.newaxis] * v

    distances = np.linalg.norm(p - closest_points, axis=1)
    return distances

p = [1, 1]  # The point 'p'
P0 = np.array([[0, 0], [2, 2], [3, 4]])
P1 = np.array([[2, 0], [4, 2], [5, 5]])
distances = point_to_line_distances(p, P0, P1)
print(distances)

[1.         1.         1.78885438]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [79]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([point_to_line_distances(p_i,P0,P1) for p_i in p]))

[[3.16381084e-01 4.14587895e+00 6.07299506e+00 1.26124583e+01
  6.36394786e+00 3.53584364e+00 1.19625384e+01 2.05482546e+00
  5.23993682e+00 4.34716553e+00]
 [5.68936570e+00 3.10317324e+00 1.15591996e+01 4.83628531e+00
  2.98737704e+00 1.76823273e+00 3.59487553e+00 6.98027249e-01
  7.91927145e+00 3.22593755e+00]
 [1.62242760e-02 5.25605207e+00 4.30554775e+00 1.36666116e+01
  6.16237575e+00 2.97531047e+00 1.32725311e+01 3.45268502e+00
  3.85366359e+00 6.26583367e+00]
 [1.25776918e+01 8.59433299e+00 9.10968128e+00 1.11029398e+00
  3.87424740e+00 4.77721832e+00 1.66386007e+00 3.84790568e+00
  3.32763363e+00 3.22705201e+00]
 [3.85270965e+00 2.98996072e+00 1.28503583e+01 1.39654943e+01
  1.19310406e+01 9.88676539e+00 1.20918074e+01 5.20531552e+00
  1.25006338e+01 1.07251195e+00]
 [7.75682153e-01 5.21489084e+00 3.76756112e+00 1.46979240e+01
  6.73231223e+00 3.35794757e+00 1.43497539e+01 3.62798564e+00
  3.68781320e+00 7.10498553e+00]
 [9.14667202e-01 2.22563121e-02 1.09367286e+01 1.17976979e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [80]:
def extract_subpart(array, center, subpart_shape, fill_value=0):
    half_height, half_width = subpart_shape[0] // 2, subpart_shape[1] // 2

    start_row = max(0, center[0] - half_height)
    end_row = min(array.shape[0], center[0] + half_height + 1)
    start_col = max(0, center[1] - half_width)
    end_col = min(array.shape[1], center[1] + half_width + 1)

    subpart = np.full(subpart_shape, fill_value)

    overlap_start_row = half_height - (center[0] - start_row)
    overlap_end_row = overlap_start_row + (end_row - start_row)
    overlap_start_col = half_width - (center[1] - start_col)
    overlap_end_col = overlap_start_col + (end_col - start_col)

    subpart[overlap_start_row:overlap_end_row, overlap_start_col:overlap_end_col] = array[start_row:end_row, start_col:end_col]

    return subpart

array = np.arange(12).reshape(3,4)
center = (1, 2)
subpart_shape = (3, 3)

subpart = extract_subpart(array, center, subpart_shape, fill_value=0)
print(subpart)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [81]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

window_size = 4
num_windows = len(Z) - window_size + 1
R = np.lib.stride_tricks.sliding_window_view(Z, window_shape=(window_size,))

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [82]:
temp = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(temp)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [83]:
temp = np.random.randint(0,10,50)
print(np.bincount(temp).argmax())

0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [84]:
matrix = np.random.rand(10, 10)

blocks = []

for i in range(8):
    for j in range(8):
        block = matrix[i:i+3, j:j+3]
        blocks.append(block)

blocks_array = np.array(blocks)
print(blocks_array)

[[[0.12759618 0.3177202  0.71272434]
  [0.73707383 0.09537916 0.74656177]
  [0.41829747 0.80751753 0.08128272]]

 [[0.3177202  0.71272434 0.78869188]
  [0.09537916 0.74656177 0.96515401]
  [0.80751753 0.08128272 0.6811497 ]]

 [[0.71272434 0.78869188 0.61401626]
  [0.74656177 0.96515401 0.12446289]
  [0.08128272 0.6811497  0.22555982]]

 [[0.78869188 0.61401626 0.85554256]
  [0.96515401 0.12446289 0.4135927 ]
  [0.6811497  0.22555982 0.18360761]]

 [[0.61401626 0.85554256 0.51549216]
  [0.12446289 0.4135927  0.39300821]
  [0.22555982 0.18360761 0.08762231]]

 [[0.85554256 0.51549216 0.14367583]
  [0.4135927  0.39300821 0.53133204]
  [0.18360761 0.08762231 0.17938286]]

 [[0.51549216 0.14367583 0.64694583]
  [0.39300821 0.53133204 0.4007723 ]
  [0.08762231 0.17938286 0.98903368]]

 [[0.14367583 0.64694583 0.45066799]
  [0.53133204 0.4007723  0.42845589]
  [0.17938286 0.98903368 0.44171046]]

 [[0.73707383 0.09537916 0.74656177]
  [0.41829747 0.80751753 0.08128272]
  [0.93833048 0.837951

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [85]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

temp1 = np.random.randint(0,10,(5,5))
S = symetric(temp1)
print(S)

[[ 7 18 12  4  4]
 [18  1  1  4 12]
 [12  1  4  4  9]
 [ 4  4  4  5  3]
 [ 4 12  9  3  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [86]:
p = 5
n = 3

matrices = [np.random.rand(n, n) for _ in range(p)]
vectors = [np.random.rand(n, 1) for _ in range(p)]
result = np.sum([np.dot(matrix, vector) for matrix, vector in zip(matrices, vectors)], axis=0)

print(result)

[[3.22930585]
 [2.79358297]
 [3.96417496]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [87]:
Z = np.random.rand(16,16)
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
print(S)

[[ 7.22400992  7.02342168  9.13422976  7.23573881]
 [ 6.02383361 10.3519737  10.29231873  8.41128965]
 [ 5.94162537  8.18385089  6.8471299   7.02867863]
 [ 7.12631785  8.91695444  9.64878357  5.53128405]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [88]:
temp = np.arange(100)
np.random.shuffle(temp)
n = 3

print (temp[np.argsort(temp)[-n:]])

[97 98 99]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [89]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [90]:
data = np.array([(1, 'Alice', 25),
                 (2, 'Bob', 30),
                 (3, 'Charlie', 28)],
                dtype=[('id', int), ('name', 'U10'), ('age', int)])

record_array = np.array(data, dtype=data.dtype)

print(record_array['id'])
print(record_array['name'])
print(record_array['age'])

[1 2 3]
['Alice' 'Bob' 'Charlie']
[25 30 28]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [91]:
Z = np.random.rand(1000)

print(np.power(Z,3))
print(Z**3)
print([x**3 for x in Z])

[2.11255031e-04 3.34126486e-02 1.07635936e-02 8.83060243e-01
 8.17569184e-01 6.46993179e-01 2.43223276e-03 3.23310887e-01
 2.08354871e-01 7.26196666e-01 2.27334530e-01 5.56305232e-01
 6.81148348e-01 8.95056563e-01 1.93108160e-02 8.78436366e-02
 1.22358873e-01 9.46891223e-02 6.88173548e-01 3.12053438e-01
 1.75370203e-01 7.59240789e-01 2.55924390e-03 5.20325407e-01
 1.19590972e-01 8.91708173e-01 2.86538659e-01 4.37881567e-03
 1.40734421e-01 1.84648022e-01 1.20957504e-02 6.27354546e-01
 1.07813744e-01 1.31163950e-03 6.88965680e-02 9.36605698e-01
 1.67774399e-01 6.40737216e-01 4.69250729e-01 2.46243720e-01
 5.52206761e-02 8.59498518e-02 2.00972025e-01 3.51342158e-01
 5.52735675e-03 5.31759162e-03 8.02717424e-02 2.36362018e-03
 3.13617198e-01 1.20774051e-03 6.96416136e-01 7.35388200e-01
 4.55438338e-01 1.87998868e-01 7.44947393e-02 7.04576053e-01
 1.97193294e-01 1.22447745e-03 2.48937402e-01 1.62315794e-01
 2.58467474e-03 2.52964727e-01 1.23755165e-01 1.15618858e-01
 3.75538428e-01 3.359661

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [92]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [93]:
temp1 = np.random.randint(0,5,(10,3))
temp2 = temp1[temp1.max(axis=1) != temp1.min(axis=1),:]
print(temp2)

[[3 2 4]
 [2 2 4]
 [0 3 0]
 [3 0 1]
 [4 1 3]
 [3 1 4]
 [4 3 2]
 [3 1 4]
 [3 4 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [94]:
temp = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(temp[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [95]:
temp1 = np.random.randint(0,3,(5,3))
temp2 = np.unique(temp1, axis=0)
print(temp2)

[[0 2 1]
 [2 0 0]
 [2 0 2]
 [2 1 2]
 [2 2 2]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [96]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)
np.einsum('i->', A)
np.einsum('i,i->i', A, B)

array([0.0133529 , 0.26845747, 0.06462473, 0.01068315, 0.20000706,
       0.57147526, 0.52947246, 0.00124624, 0.08821543, 0.41483687])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [97]:
temp1= np.random.randint(0,5,(16,4))
n = 7
temp2 = np.logical_and.reduce(np.mod(temp1, 1) == 0, axis=-1)
temp2 &= (temp1.sum(axis=-1) == n)
print(temp1[temp2])

[[2 0 1 4]
 [0 4 2 1]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [98]:
temp = np.random.randn(100)
N = 1000
idx = np.random.randint(0, temp.size, (N, temp.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)


TypeError: only integer scalar arrays can be converted to a scalar index